#version 430
layout(local_size_x = 8​, local_size_y = 8​) in;

uniform readonly image2D gColor;
uniform writeonly image2D potatoImg;

void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    vec4 pColor = imageLoad(gColor, pixelCoords);
    
    ivec2 newCoords = ivec2(gl_WorkGroupID.xy * gl_WorkGroupSize.xy + (gl_WorkGroupSize.xy - gl_LocalInvocationID.xy));
    
    imageStore(potatoImg, newCoords, pColor);
}
