[
    {
        "name" : "GBufferDebugFill.vertexShader",
        "type" : "vertex-shader",
        "file" : "GBufferDebugFill.vert"
    },
    {
        "name" : "GBufferDebugFill.fragmentShader",
        "type" : "fragment-shader",
        "file" : "GBufferDebugFill.frag"
    },
    {
        "name" : "GBufferDebugFill.shaderProgram",
        "type" : "shader-program",
        "file" : "GBufferDebugFill.prog"
    }
]
