[
    {
        "name" : "ScreenTexture.vertexShader",
        "type" : "vertex-shader",
        "file" : "ScreenTexture.vert"
    },
    {
        "name" : "ScreenTexture.fragmentShader",
        "type" : "fragment-shader",
        "file" : "ScreenTexture.frag"
    },
    {
        "name" : "ScreenTexture.shaderProgram",
        "type" : "shader-program",
        "file" : "ScreenTexture.prog"
    }
]
