[
    {
        "name" : "SimpleTextured.vertexShader",
        "type" : "vertex-shader",
        "file" : "SimpleTextured.vert"
    },
    {
        "name" : "SimpleTextured.fragmentShader",
        "type" : "fragment-shader",
        "file" : "SimpleTextured.frag"
    },
    {
        "name" : "SimpleTextured.shaderProgram",
        "type" : "shader-program",
        "file" : "SimpleTextured.prog"
    }
]