[
    {
        "name" : "SimpleVertexColor.vertexShader",
        "type" : "vertex-shader",
        "file" : "SimpleVertexColor.vert"
    },
    {
        "name" : "SimpleVertexColor.fragmentShader",
        "type" : "fragment-shader",
        "file" : "SimpleVertexColor.frag"
    },
    {
        "name" : "SimpleVertexColor.shaderProgram",
        "type" : "shader-program",
        "file" : "SimpleVertexColor.prog"
    }
]
