[
    {
        "name" : "TestInstanced.vertexShader",
        "type" : "vertex-shader",
        "file" : "TestInstanced.vert"
    },
    {
        "name" : "TestInstanced.fragmentShader",
        "type" : "fragment-shader",
        "file" : "TestInstanced.frag"
    },
    {
        "name" : "TestInstanced.shaderProgram",
        "type" : "shader-program",
        "file" : "TestInstanced.prog"
    }
]