[
    {
        "name" : "TestNormalMap.vertexShader",
        "type" : "vertex-shader",
        "file" : "TestNormalMap.vert"
    },
    {
        "name" : "TestNormalMap.fragmentShader",
        "type" : "fragment-shader",
        "file" : "TestNormalMap.frag"
    },
    {
        "name" : "TestNormalMap.shaderProgram",
        "type" : "shader-program",
        "file" : "TestNormalMap.prog"
    }
]