[
    {
        "name" : "smac.Tonemapper.vertexShader",
        "type" : "vertex-shader",
        "file" : "Tonemapper.vert"
    },
    {
        "name" : "smac.Tonemapper.fragmentShader",
        "type" : "fragment-shader",
        "file" : "Tonemapper.frag"
    },
    {
        "name" : "smac.Tonemapper.shaderProgram",
        "type" : "shader-program",
        "file" : "Tonemapper.prog"
    }
]
