[
    {
        "name" : "SunDepthDebug.vertexShader",
        "type" : "vertex-shader",
        "file" : "SunDepthDebug.vert"
    },
    {
        "name" : "SunDepthDebug.fragmentShader",
        "type" : "fragment-shader",
        "file" : "SunDepthDebug.frag"
    },
    {
        "name" : "SunDepthDebug.shaderProgram",
        "type" : "shader-program",
        "file" : "SunDepthDebug.prog"
    }
]
