#version 430
layout(local_size_x = 8, local_size_y = 8) in;

layout(std430) buffer CounterBuffer {
    uint count;
};

layout(std430) buffer InstanceBuffer {
    uint instanceCoords[];
};

layout(rgba16f) uniform image2D instanceImage;

void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    
    vec4 pColor = imageLoad(instanceImage, pixelCoords);
    
    if(pColor.r > 0) {
        uint ii = atomicAdd(count, 1);
        
        instanceCoords[ii] = pixelCoords.x | (pixelCoords.y << 16);
    }
    
}
