#version 430
layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0) uniform atomic_uint count;

layout(std430) buffer InstanceBuffer {
    uint instanceCoords[];
};

layout(rgba16f) uniform image2D instanceImage;

void main() {
    
    //atomicExchange(count, instanceCoords.length());
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    
    vec4 pColor = imageLoad(instanceImage, pixelCoords);
    
    if(pColor.r > 0) {
        uint ii = atomicCounterIncrement(count);
        atomicExchange(instanceCoords[0], ii);
        
        
        /*
        if(ii < instanceCoords.length()) {
            instanceCoords[0] = pixelCoords.x | (pixelCoords.y << 16);
        }
        */
    }
    
}
