[
    {
        "name" : "sho.Postprocess.vertexShader",
        "type" : "vertex-shader",
        "file" : "Postprocess.vert"
    },
    {
        "name" : "sho.Postprocess.fragmentShader",
        "type" : "fragment-shader",
        "file" : "Postprocess.frag"
    },
    {
        "name" : "sho.Postprocess.shaderProgram",
        "type" : "shader-program",
        "file" : "Postprocess.prog"
    }
]
