[
    {
        "name" : "Tessellate.vertexShader",
        "type" : "vertex-shader",
        "file" : "Tessellate.vert"
    },
    {
        "name" : "Tessellate.tessControlShader",
        "type" : "tess-control-shader",
        "file" : "Tessellate.control"
    },
    {
        "name" : "Tessellate.tessEvaluationShader",
        "type" : "tess-evaluation-shader",
        "file" : "Tessellate.eval"
    },
    {
        "name" : "Tessellate.fragmentShader",
        "type" : "fragment-shader",
        "file" : "Tessellate.frag"
    },
    {
        "name" : "Tessellate.shaderProgram",
        "type" : "shader-program",
        "file" : "Tessellate.prog"
    }
]
